print ("Hello! This is a story about a young adventurer.")
name = input ("First enter the name of this adventurer: ")
if name == "Trey":
    print ("WOW! I LOVE that name!!!!!! But now name the town they live in.")
else:
    print (f"{name}! What an amazing name! Now, name the town that {name} is coming from.")
town = input ("Enter here: ")
print (f"Okay, last few things so that {name} can begin their journey.")
companion = input ("Please enter the name of their companion: ")
print ("Hey I know that guy!")
food = input (f"Enter {name}'s favorite food: ")
if food == "chocolate milk":
    print ("OH WOW! ME TOO!")
    print (f"Ok, moving on, {name} and {companion} are leaving {town} to embark on an awesome journey.")
else:
    print (f"Ok so {name} and {companion} are leaving {town} to embark on an awesome journey.")
input ("")
print (f"One day, {name} was on their daily walk in {town} when they discovered a...")
discovery1 = input ("Enter Here: ")
print (f"{discovery1}!!!!!!")
print (f"It was so scary that {name} ran all the way to their friend, {companion}'s house.")
input ("")
print (f"{companion}, worried, let them in and asked what was wrong. When told about the {discovery1}, {companion} insisted they must confront it.")
input ("")
print (f"They ran back, only to discover the {discovery1} was missing!")
input ("")
print (f"After taking a breather, {name} and {companion} decided what to do. They ended up deciding to leave the town.")
input ("")
print (f"They gathered a few items before leaving {town}, which included a sword, a shield and {food}.")
input ("")
print (f"{name} led the way, sword in hand. After only a few hours of walking, they sat down to eat their {food}.")
input ("")
print (f"Finally, after the sun had already set, they found the {discovery1}.")
battle_line = input (f"Enter what {name} said upon finding the {discovery1}:")
print (f"Sword raised, {name} bravely yelled \"{battle_line}\"")
input ("")
print (f"With the help of {companion}, they both defeated the {discovery1} easily.")
input ("")
print ("The end!!!!!!!!!!!")